### ISSUE TITLE
implemente el modulo de contabilidad

### ISSUE THREAD

**Issue by zombozo** [zombozo/senes-proteges#22]
### esta compuesto por los siguientes requisitos:

- [ ] El sistema debe contener un modulo para llevar la contabilidad del asilo, que gestionara las facturas, los servicios del asilo, las donaciones, 

- [ ] El modulo de contabilidad debe informar de las deudas pendientes a familiares del paciente mediante correos electronicos.

- [ ] El modulo de contabilidad debe registrar las donaciones, para poder hacerlo los donantes deben contar con un perfil en el sistema, a este perfil se asociaran las donaciones que realice a lo largo del tiempo.

**Comment by zombozo** [comment]
![diagramas senes-proteges-casos de uso manejo de caja](https://user-images.githubusercontent.com/15509293/175168124-6f19f03a-23ff-4ac3-84d0-0e0fa13db15a.png)
